# Generated by Django 2.0.6 on 2018-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180610_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pending_payout',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
