# Generated by Django 2.0.6 on 2018-06-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180617_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pending_payout',
            new_name='pending_payouts',
        ),
    ]
