# Generated by Django 2.0.6 on 2018-07-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
