# Generated by Django 2.0.6 on 2018-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20180701_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('manufacturer_url', models.URLField(max_length=800, null=True)),
                ('image_url', models.URLField(null=True)),
                ('search_term', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('pieces', models.CharField(blank=True, max_length=200, null=True)),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
